export const businessProfileSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "companyName",
    "phone",
    "email",
    "services",
    "serviceAreas",
    "financingMentioned",
    "emergencyServiceMentioned",
    "maintenancePlanMentioned",
    "brandTone",
    "differentiators",
    "growthScore",
    "topGrowthOpportunities",
    "primaryColor",
    "secondaryColor",
    "accentColor",
    "logoUrl",
    "heroImageUrl",
    "brandStyle",
    "seoAnalysis",
    "aiSeoAnalysis",
  ],
  properties: {
    companyName: { type: "string" },
    phone: { type: "string" },
    email: { type: "string" },
    services: { type: "array", items: { type: "string" } },
    serviceAreas: { type: "array", items: { type: "string" } },
    financingMentioned: { type: "boolean" },
    emergencyServiceMentioned: { type: "boolean" },
    maintenancePlanMentioned: { type: "boolean" },
    brandTone: { type: "string" },
    differentiators: { type: "array", items: { type: "string" } },
    growthScore: { type: "number" },
    topGrowthOpportunities: {
      type: "array",
      items: { type: "string" },
    },
    primaryColor: { type: "string" },
    secondaryColor: { type: "string" },
    accentColor: { type: "string" },
    logoUrl: { type: "string" },
    heroImageUrl: { type: "string" },
    brandStyle: { type: "string" },
    seoAnalysis: {
      type: "object",
      additionalProperties: false,
      required: [
        "score",
        "titleTag",
        "metaDescription",
        "localSeoGaps",
        "technicalIssues",
        "contentOpportunities",
        "keywordUpdates",
        "recommendedPages",
        "recommendedFixes",
      ],
      properties: {
        score: { type: "number" },
        titleTag: { type: "string" },
        metaDescription: { type: "string" },
        localSeoGaps: { type: "array", items: { type: "string" } },
        technicalIssues: { type: "array", items: { type: "string" } },
        contentOpportunities: { type: "array", items: { type: "string" } },
        keywordUpdates: {
          type: "array",
          items: {
            type: "object",
            additionalProperties: false,
            required: ["currentText", "suggestedText", "page", "reason"],
            properties: {
              currentText: { type: "string" },
              suggestedText: { type: "string" },
              page: { type: "string" },
              reason: { type: "string" },
            },
          },
        },
        recommendedPages: {
          type: "array",
          items: {
            type: "object",
            additionalProperties: false,
            required: ["title", "slug", "searchIntent", "priority", "rationale"],
            properties: {
              title: { type: "string" },
              slug: { type: "string" },
              searchIntent: { type: "string" },
              priority: { type: "string", enum: ["High", "Medium", "Low"] },
              rationale: { type: "string" },
            },
          },
        },
        recommendedFixes: {
          type: "array",
          items: {
            type: "object",
            additionalProperties: false,
            required: ["problem", "fix", "priority", "impact", "effort"],
            properties: {
              problem: { type: "string" },
              fix: { type: "string" },
              priority: { type: "string", enum: ["High", "Medium", "Low"] },
              impact: { type: "string" },
              effort: { type: "string", enum: ["Quick", "Moderate", "Heavy"] },
            },
          },
        },
      },
    },
    aiSeoAnalysis: {
      type: "object",
      additionalProperties: false,
      required: [
        "score",
        "answerEngineReadiness",
        "citationOpportunities",
        "schemaRecommendations",
        "faqQuestions",
        "entityGaps",
        "recommendedFixes",
      ],
      properties: {
        score: { type: "number" },
        answerEngineReadiness: { type: "string" },
        citationOpportunities: { type: "array", items: { type: "string" } },
        schemaRecommendations: { type: "array", items: { type: "string" } },
        faqQuestions: { type: "array", items: { type: "string" } },
        entityGaps: { type: "array", items: { type: "string" } },
        recommendedFixes: {
          type: "array",
          items: {
            type: "object",
            additionalProperties: false,
            required: ["problem", "fix", "priority", "impact", "effort"],
            properties: {
              problem: { type: "string" },
              fix: { type: "string" },
              priority: { type: "string", enum: ["High", "Medium", "Low"] },
              impact: { type: "string" },
              effort: { type: "string", enum: ["Quick", "Moderate", "Heavy"] },
            },
          },
        },
      },
    },
  },
} as const;

export const campaignSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "facebookAd",
    "googleBusinessProfilePost",
    "emailCampaign",
    "seoPageRecommendation",
    "aiSeoRecommendation",
    "landingPageHero",
  ],
  properties: {
    facebookAd: { type: "string" },
    googleBusinessProfilePost: { type: "string" },
    emailCampaign: { type: "string" },
    seoPageRecommendation: { type: "string" },
    aiSeoRecommendation: { type: "string" },
    landingPageHero: {
      type: "object",
      additionalProperties: false,
      required: ["headline", "subheadline", "primaryCta", "supportingBullets"],
      properties: {
        headline: { type: "string" },
        subheadline: { type: "string" },
        primaryCta: { type: "string" },
        supportingBullets: {
          type: "array",
          items: { type: "string" },
        },
      },
    },
  },
} as const;
