export const businessProfileSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "companyName",
    "phone",
    "email",
    "services",
    "serviceAreas",
    "financingMentioned",
    "emergencyServiceMentioned",
    "maintenancePlanMentioned",
    "brandTone",
    "differentiators",
    "growthScore",
    "topGrowthOpportunities",
    "primaryColor",
    "secondaryColor",
    "accentColor",
    "logoUrl",
    "heroImageUrl",
    "brandStyle",
  ],
  properties: {
    companyName: { type: "string" },
    phone: { type: "string" },
    email: { type: "string" },
    services: { type: "array", items: { type: "string" } },
    serviceAreas: { type: "array", items: { type: "string" } },
    financingMentioned: { type: "boolean" },
    emergencyServiceMentioned: { type: "boolean" },
    maintenancePlanMentioned: { type: "boolean" },
    brandTone: { type: "string" },
    differentiators: { type: "array", items: { type: "string" } },
    growthScore: { type: "number" },
    topGrowthOpportunities: {
      type: "array",
      items: { type: "string" },
    },
    primaryColor: { type: "string" },
    secondaryColor: { type: "string" },
    accentColor: { type: "string" },
    logoUrl: { type: "string" },
    heroImageUrl: { type: "string" },
    brandStyle: { type: "string" },
  },
} as const;

export const campaignSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "facebookAd",
    "googleBusinessProfilePost",
    "emailCampaign",
    "seoPageRecommendation",
    "landingPageHero",
  ],
  properties: {
    facebookAd: { type: "string" },
    googleBusinessProfilePost: { type: "string" },
    emailCampaign: { type: "string" },
    seoPageRecommendation: { type: "string" },
    landingPageHero: {
      type: "object",
      additionalProperties: false,
      required: ["headline", "subheadline", "primaryCta", "supportingBullets"],
      properties: {
        headline: { type: "string" },
        subheadline: { type: "string" },
        primaryCta: { type: "string" },
        supportingBullets: {
          type: "array",
          items: { type: "string" },
        },
      },
    },
  },
} as const;
