"use client";

import { Bot, CalendarDays, CheckCircle2, Copy, FileText, ImageIcon, Loader2, MessageSquareText, Send, Sparkles } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { BusinessProfile } from "@/lib/types";
import { Button, Eyebrow, Panel } from "@/components/ui";

type ContentView = "generate-my-week" | "content-library" | "ai-team";
type Asset = { id: string; channel: string; title: string; body: string; cta: string; scheduledFor: string };
type Week = { id: string; createdAt: string; focus: string; theme: string; strategicNote: string; assets: Asset[] };
const storageKey = "hvac-growth-os-weekly-content-v1";

export function WeeklyContentEngine({ analysis, initialView, setActiveSection }: { analysis: BusinessProfile; initialView: ContentView; setActiveSection: (section: ContentView) => void }) {
  const [focus, setFocus] = useState("seasonal service demand and homeowner trust");
  const [plans, setPlans] = useState<Week[]>([]);
  const [activePlan, setActivePlan] = useState<Week | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [copied, setCopied] = useState("");

  useEffect(() => { try { setPlans(JSON.parse(window.localStorage.getItem(storageKey) || "[]") as Week[]); } catch { setPlans([]); } }, []);
  useEffect(() => { window.localStorage.setItem(storageKey, JSON.stringify(plans)); }, [plans]);

  const counts = useMemo(() => {
    const assets = activePlan?.assets || [];
    return ["Facebook / Instagram", "Google Business Profile", "Blog", "Email", "SMS", "Image concept"].map((channel) => ({ channel, count: assets.filter((asset) => asset.channel === channel).length }));
  }, [activePlan]);

  function generate() {
    setIsGenerating(true);
    window.setTimeout(() => {
      const plan = buildStarterWeek(analysis, focus);
      setPlans((current) => [plan, ...current]);
      setActivePlan(plan);
      setIsGenerating(false);
    }, 650);
  }
  async function copyAsset(asset: Asset) {
    await navigator.clipboard.writeText(`${asset.title}\n\n${asset.body}\n\n${asset.cta}`);
    setCopied(asset.id); window.setTimeout(() => setCopied(""), 1600);
  }

  if (initialView === "ai-team") return <AiTeam setActiveSection={setActiveSection} />;
  if (initialView === "content-library") return <ContentLibrary plans={plans} onOpen={setActivePlan} activePlan={activePlan} />;

  return <section className="space-y-5">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><Eyebrow>Content Operations</Eyebrow><h2 className="text-3xl font-black text-ink">Generate My Week</h2><p className="mt-2 max-w-2xl text-sm font-medium text-graphite/70">One focused weekly draft pack for {analysis.companyName || "your HVAC company"}: social, GBP, email, SMS, blogs, and creative direction.</p></div><div className="rounded-full bg-teal-50 px-4 py-2 text-sm font-black text-teal-800">Draft mode · human review required</div></div>
    <Panel className="p-5"><div className="grid gap-4 lg:grid-cols-[1fr_auto]"><label className="grid gap-2 text-sm font-black text-ink"><span>What should this week focus on?</span><input className="h-12 rounded-xl border border-ink/15 bg-white px-4 font-medium outline-none focus:border-teal-500" value={focus} onChange={(event) => setFocus(event.target.value)} /></label><div className="self-end"><Button onClick={generate} disabled={isGenerating}>{isGenerating ? <Loader2 className="size-4 animate-spin" /> : <Sparkles className="size-4" />}{isGenerating ? "Building your week..." : "Generate My Week"}</Button></div></div><p className="mt-3 text-xs font-semibold text-graphite/60">This safe starter mode creates editable local drafts from the business profile. No publishing or external posting occurs.</p></Panel>
    {activePlan ? <><Panel className="overflow-hidden p-0"><div className="bg-gradient-to-r from-ink to-teal-700 p-6 text-white"><p className="text-xs font-black uppercase tracking-[.18em] text-teal-100">This week&apos;s strategic theme</p><h3 className="mt-2 text-2xl font-black">{activePlan.theme}</h3><p className="mt-2 max-w-3xl text-sm font-medium text-teal-50">{activePlan.strategicNote}</p></div><div className="grid gap-px bg-ink/10 sm:grid-cols-3 lg:grid-cols-6">{counts.map((item) => <div className="bg-white px-4 py-4" key={item.channel}><p className="text-2xl font-black text-ink">{item.count}</p><p className="text-xs font-bold text-graphite/65">{item.channel}</p></div>)}</div></Panel><div className="grid gap-4 lg:grid-cols-2">{activePlan.assets.map((asset) => <Panel className="p-5" key={asset.id}><div className="flex items-start justify-between gap-3"><div><span className="rounded-full bg-teal-50 px-2.5 py-1 text-xs font-black text-teal-800">{asset.channel}</span><h3 className="mt-3 text-lg font-black text-ink">{asset.title}</h3></div><span className="text-xs font-bold text-graphite/55">{asset.scheduledFor}</span></div><p className="mt-3 whitespace-pre-line text-sm leading-6 text-graphite/80">{asset.body}</p><div className="mt-4 flex items-center justify-between border-t border-ink/10 pt-3"><span className="text-sm font-black text-ink">{asset.cta}</span><button className="inline-flex items-center gap-1.5 text-sm font-black text-teal-700 hover:text-ink" onClick={() => void copyAsset(asset)} type="button">{copied === asset.id ? <CheckCircle2 className="size-4" /> : <Copy className="size-4" />}{copied === asset.id ? "Copied" : "Copy"}</button></div></Panel>)}</div></> : <EmptyWeek />}
  </section>;
}

function EmptyWeek() { return <Panel className="border-dashed p-10 text-center"><CalendarDays className="mx-auto size-9 text-teal-600" /><h3 className="mt-3 text-xl font-black text-ink">Your next week starts here.</h3><p className="mx-auto mt-2 max-w-lg text-sm font-medium text-graphite/65">Choose a timely focus, generate the pack, then review and copy each asset into the channels you already use.</p></Panel>; }
function ContentLibrary({ plans, onOpen, activePlan }: { plans: Week[]; onOpen: (plan: Week) => void; activePlan: Week | null }) { return <section className="space-y-5"><div><Eyebrow>Reusable Drafts</Eyebrow><h2 className="text-3xl font-black text-ink">Content Library</h2><p className="mt-2 text-sm font-medium text-graphite/70">Saved locally in this browser until tenant storage is connected.</p></div>{plans.length ? <div className="grid gap-4 lg:grid-cols-2">{plans.map((plan) => <Panel className="p-5" key={plan.id}><p className="text-xs font-black uppercase tracking-[.15em] text-copper">{new Date(plan.createdAt).toLocaleDateString()}</p><h3 className="mt-2 text-xl font-black text-ink">{plan.theme}</h3><p className="mt-2 text-sm text-graphite/70">{plan.assets.length} editable assets · {plan.focus}</p><div className="mt-5"><Button onClick={() => onOpen(plan)}><FileText className="size-4" />Open pack</Button></div></Panel>)}</div> : <EmptyWeek />}{activePlan && <Panel className="p-5"><h3 className="font-black text-ink">Open pack: {activePlan.theme}</h3><p className="mt-1 text-sm text-graphite/70">Use Generate My Week to view and copy every draft.</p></Panel>}</section>; }
function AiTeam({ setActiveSection }: { setActiveSection: (section: ContentView) => void }) { const agents = [[Bot,"AI CMO","Sets the weekly strategic priority."],[MessageSquareText,"Social Media Manager","Shapes Facebook and Instagram drafts."],[Send,"GBP Manager","Keeps local business updates fresh."],[FileText,"SEO Strategist","Plans educational blog content."],[MessageSquareText,"Email Specialist","Builds retention and reactivation email."],[MessageSquareText,"SMS Specialist","Creates concise service follow-ups."],[ImageIcon,"Creative Director","Defines visual concepts for review."]]; return <section><Eyebrow>Orchestrated AI Team</Eyebrow><h2 className="text-3xl font-black text-ink">Specialists, not a black box.</h2><p className="mt-2 max-w-2xl text-sm font-medium text-graphite/70">Each role contributes to the weekly brief; publishing remains explicitly human-approved.</p><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{agents.map(([Icon, title, detail]) => { const AgentIcon = Icon as typeof Bot; return <Panel className="p-5" key={String(title)}><AgentIcon className="size-6 text-teal-700" /><h3 className="mt-4 font-black text-ink">{title as string}</h3><p className="mt-2 text-sm text-graphite/70">{detail as string}</p></Panel>; })}</div><div className="mt-5"><Button onClick={() => setActiveSection("generate-my-week")}><Sparkles className="size-4" />Create a weekly brief</Button></div></section>; }
function buildStarterWeek(profile: BusinessProfile, focus: string): Week { const service = profile.services[0] || "home comfort service"; const city = profile.serviceAreas[0] || "your local area"; const company = profile.companyName || "Your HVAC Company"; const items: Array<[string, string, string]> = [["Facebook / Instagram","Mon","The small signs your system may need attention before a no-cool day."],["Facebook / Instagram","Tue",`A homeowner-first look at ${service.toLowerCase()} in ${city}.`],["Facebook / Instagram","Wed","Behind the service call: what a thorough visit should include."],["Facebook / Instagram","Thu","A simple comfort tip homeowners can use this week."],["Facebook / Instagram","Fri","Weekend comfort checklist for busy households."],["Google Business Profile","Mon",`Local ${service.toLowerCase()} help for homeowners in ${city}.`],["Google Business Profile","Tue","A practical service reminder before peak demand."],["Google Business Profile","Wed","What to expect when you request HVAC service."],["Google Business Profile","Thu","Comfort advice from a local service team."],["Google Business Profile","Fri","Make your next service visit easier with this checklist."],["Blog","Flexible",`When should a homeowner call for ${service.toLowerCase()}?`],["Blog","Flexible",`How to prepare your home for seasonal HVAC demand in ${city}.`],["Email","Wed","Your weekly home comfort note: simple signs worth checking."],["SMS","Mon","A quick service reminder for homeowners."],["SMS","Tue","A short seasonal comfort tip."],["SMS","Wed","A follow-up ready for service customers."],["SMS","Thu","A maintenance-focused homeowner reminder."],["SMS","Fri","A friendly weekend comfort check-in."], ...Array.from({ length: 10 }, (_, index) => ["Image concept", "Flexible", `Premium HVAC visual ${index + 1}: technician, homeowner, and ${service.toLowerCase()} context with clear negative space for approved copy.`] as [string, string, string])]; return { id: crypto.randomUUID(), createdAt: new Date().toISOString(), focus, theme: `Own the ${service.toLowerCase()} conversation this week`, strategicNote: `Build trust before urgency. Every asset supports ${focus} while staying grounded in ${company}'s real services and local market.`, assets: items.map(([channel, scheduledFor, title], index) => ({ id: `${index}-${crypto.randomUUID()}`, channel, title, scheduledFor, body: channel === "Image concept" ? `${title}\n\nVisual direction only — no typography, logos, offers, or unverified claims in-image.` : `${company} is sharing a useful homeowner note for ${city}: ${title} Keep it practical, calm, and centered on the next best step for the homeowner.`, cta: channel === "Image concept" ? "Review creative direction" : "Request service when you need help" })) }; }
